// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://roocapjgrdhvyvlogdjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvb2NhcGpncmRodnl2bG9nZGpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2OTY1NDgsImV4cCI6MjA3MTI3MjU0OH0.k5bj832_Y5C5YTrzHIHMh8AyvNpgPNpkSA2l8rnzRiM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});